package rules.letovi;
import com.ftn.sbnz.model.FlightEvent;
import com.ftn.sbnz.model.RunWay;

rule "letovi"
    when
        $e1: FlightEvent($runway:  runWay)
        $e2: FlightEvent(
            this != $e1,
            runWay == $runway,
            this after[0, 3m] $e1
        )

    then
        RunWay runWay = new RunWay("My Run Way 2");
        insert(runWay);
        modify($e2){
            setRunWay(runWay);
        }
end
